name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Up Laravel Sail
      run: ./vendor/bin/sail up -d

    - name: Install Dependencies
      run: ./vendor/bin/sail composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run migrations
      env:
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: testing
      run: ./vendor/bin/sail artisan migrate

    - name: Execute tests (Unit and Feature tests) using PEST
      run: ./vendor/bin/sail --coverage-clover=build/logs/clover.xml

    - name: Upload coverage to Coveralls
      run: ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
