name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: 'mysql/mysql-server:8.0'
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Execute tests (Unit and Feature tests) using PEST
      env:
        DB_PORT: 3306
        DB_DATABASE: testing

    - name: Run tests with coverage
      run: php artisan test --coverage-clover=build/logs/clover.xml

    - name: Upload coverage to Coveralls
      run: php-coveralls --coverage_clover=build/logs/clover.xml -v
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
