name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Copy .env
      run: cp .env.ci .env

    - name: Composer install
      run: composer install

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Up Sail
      run: docker-compose up -d

    - name: Install Dependencies
      run: docker-compose exec -it laravel.test bash -c 'composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist'

    - name: Run migrations
      run: docker-compose exec -it laravel.test bash -c 'php artisan migrate'

    - name: Execute tests (Unit and Feature tests) using PEST
      run: ./vendor/bin/sail pest --coverage-clover=build/logs/clover.xml

    - name: Upload coverage to Coveralls
      run: ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
